### ISSUE TITLE
Defining lifetime option in SplitTest.init does nothing

### ISSUE THREAD

**Issue by Helen-Mobify** [mobify/split-test#7]
When initializing split test with the lifetime option, the cookie will always set to 30 days regardless what the lifetime options is set to.

This is due to `lifetime` not being passed in from `setChoice` to `setCookie`.

```js
    SplitTest.prototype.setChoice = SplitTest.prototype.setValue = function(value) {
        // Splits are stored for 30 days.
        SplitTest.setCookie(this.cookieName, value, this.cookieDomain);
    };
```

**Comment by jansepar** [comment]
@Helen-Mobify nice catch! Do you have any time to open up a PR to address the issue yourself?

**Comment by donnielrt** [comment]
Issue seems to have been resolved with Helen's fix.
